baseURL = "http://localhost:1313/"
languageCode = "ko"
title = "SHY Portfolio"
theme = "sans"
publishDir = "public"

enableRobotsTXT = true
summaryLength = 40
hasCJKLanguage = true
removePathAccents = true
defaultMarkdownHandler = "goldmark"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

  [markup.highlight]
    style = "monokai"
    lineNos = false
    lineNumbersInTable = false
